// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYzauF6-QZ_PKPAcrGNQkXJQ9k0zxZYc4',
    appId: '1:323137335762:web:61d4158da80f19877b580b',
    messagingSenderId: '323137335762',
    projectId: 'dateapp-3531c',
    authDomain: 'dateapp-3531c.firebaseapp.com',
    storageBucket: 'dateapp-3531c.appspot.com',
    measurementId: 'G-VF72HY7FMK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdmf4V0O_xHLoBug33dzX5_0jIrc0H1EQ',
    appId: '1:323137335762:android:e566b6e800f218117b580b',
    messagingSenderId: '323137335762',
    projectId: 'dateapp-3531c',
    storageBucket: 'dateapp-3531c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-rAcKeKGY36h7MRKKv-gx0MZufQTLh2A',
    appId: '1:323137335762:ios:c5eee110ea7556697b580b',
    messagingSenderId: '323137335762',
    projectId: 'dateapp-3531c',
    storageBucket: 'dateapp-3531c.appspot.com',
    iosClientId: '323137335762-caspnnorvk55q3tba4suiu0i86jtpg9m.apps.googleusercontent.com',
    iosBundleId: 'com.example.date',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-rAcKeKGY36h7MRKKv-gx0MZufQTLh2A',
    appId: '1:323137335762:ios:c5eee110ea7556697b580b',
    messagingSenderId: '323137335762',
    projectId: 'dateapp-3531c',
    storageBucket: 'dateapp-3531c.appspot.com',
    iosClientId: '323137335762-caspnnorvk55q3tba4suiu0i86jtpg9m.apps.googleusercontent.com',
    iosBundleId: 'com.example.date',
  );
}
